### ISSUE TITLE
outdated backward-cpp

### ISSUE THREAD

**Issue by v4hn** [facontidavide/PlotJuggler#277]
Your 3rd party version of backward-cpp is outdated and fails to build with binutils 2.34.
https://github.com/bombela/backward-cpp/pull/165 fixed this problem upstream.

Could you pull this fix (or the current version for that matter)?

Alternatively this seems to be the standard use-case of git submodules, although I'm not a big fan of those myself.

**Comment by facontidavide** [comment]
done

**Comment by v4hn** [comment]
Looks like you missed a file `BackwardConfig.config`?
The build fails complaining that the file is referenced in `CMakeLists.txt` but does not exist.

**Comment by facontidavide** [comment]
fixed
